version: '3'
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: bluray
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ../data:/var/lib/csv
